OFS-146: get contribution length for contract
openimis/openimis-be-contribution_plan_py pull request #22
Opened 2021-02-03 16:26 UTC by sniedzielski

In that PR I want to add getter 

GetContributionLength
- send a signal
- read the signal result, if >0 take that result as duration in month else take periodicity instead

according to the wiki page https://openimis.atlassian.net/wiki/spaces/OP/pages/1730740245/Contribution+plan+and+contribution+plan+bundle+Module

2021-02-04 16:57 UTC, delcroip requested changes

2021-02-04 16:57 UTC, delcroip commented on contribution_plan/signals.py
> +def on_get_contribution_length_signal(sender, **kwargs):
This will be in the calculation rule module not here because grace period will be (or not) defined in the calculation rule,

2021-02-04 16:57 UTC, delcroip commented on contribution_plan/services.py
> +    signal_result = get_contribution_length_signal.send(sender=ContributionPlanModel, contribution_plan=contribution_plan)[0][1]
Here I would add in the CP model
length :float = None

then get_contribution_length will the a CP method
self.length = self.periodicity
get_contribution_length_signal.send(sender=self.__class__, instance=self) # not sure instance is required
return self.length

2021-02-04 16:59 UTC, delcroip commented on contribution_plan/services.py
> +    signal_result = get_contribution_length_signal.send(sender=ContributionPlanModel, contribution_plan=contribution_plan)[0][1]
you were not using signal_result

2021-02-05 15:03 UTC, sniedzielski commented
@delcroip remigrate to contribution plan as we discussed.

2021-02-05 15:31 UTC, delcroip approved these changes

2021-02-05 15:31 UTC, merged